### ISSUE TITLE
Gradle

### ISSUE THREAD

**Issue by kristofferso** [aleksolberg/SpotifyMatcher#1]
Jeg tror problemet er bruken av Gradle sammen med Docker. 
https://stackoverflow.com/questions/61108021/gradle-and-docker-how-to-run-a-gradle-build-within-docker-container

@aleksolberg

**Comment by aleksolberg** [comment]
Har fått noen ekstra slides på hvordan man gjør denne typen ting ordentlig, så skal se på det etterhvert.

**Comment by aleksolberg** [comment]
Får nå til å kjøre image med alle tre containers.
